// 添加所需的图标
import {
  MailOutline,
  UserOutline,
  MenuFoldOutline,
  LockOutline,
  HomeOutline,
  TeamOutline,
  QuestionCircleOutline,
  CrownOutline,
  PayCircleOutline,
  EditOutline,
  IdcardOutline,
  TableOutline,
  SettingOutline,
  MenuUnfoldOutline,
  SearchOutline,
  ReloadOutline,
  InboxOutline,
  FolderOpenOutline,
  RedoOutline,
  UndoOutline,
  SyncOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  CloudUploadOutline
} from "@ant-design/icons-angular/icons";

export const ICONS = [
  MailOutline,
  UserOutline,
  MenuFoldOutline,
  LockOutline,
  HomeOutline,
  TeamOutline,
  QuestionCircleOutline,
  CrownOutline,
  PayCircleOutline,
  EditOutline,
  IdcardOutline,
  TableOutline,
  SettingOutline,
  MenuUnfoldOutline,
  SearchOutline,
  ReloadOutline,
  InboxOutline,
  FolderOpenOutline,
  RedoOutline,
  UndoOutline,
  SyncOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  CloudUploadOutline
];
